package logrz

import "testing"

func TestLogger(t *testing.T) {
	SetUseFile(true, true, "./file.example")
	SetLevel(TraceLevel)
	DisableColor(true)
	T("Start!")
	D("Start!")
	I("Start!")
	W("Start!")
	E("Start!")
	F("Start!")
	P("Start!")
	DisableColor(false)
	SetUseFile(true, false, "./file.example")
	T("Start!")
	D("Start!")
	I("Start!")
	W("Start!")
	E("Start!")
	F("Start!")
	P("Start!")
	ForceFullColor(true)
	T("Start!")
	D("Start!")
	I("Start!")
	W("Start!")
	E("Start!")
	F("Start!")
	P("Start!")
	DisableColor(true)
	ForceFullColor(true)
	T("Start!")
	D("Start!")
	I("Start!")
	W("Start!")
	E("Start!")
	F("Start!")
	P("Start!")
}
